#服务器配置
server:
  port: 8087
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accesslog:
      enabled: true

spring:
  profiles:
    active: prod

mybatis:
  check-config-location: true
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/surl?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 8087
---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:××/surl?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ×××
    password: ×××